name: Build and Request Approval

on:
  push:
    tags:
      - '*'  # O workflow será acionado em qualquer tag criada

jobs:
  build-and-approve:
    name: Build and Approve
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Atualizado para usar Node.js 20

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Atualizado para usar Node.js 20
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Package Extension
        run: |
          npm install -g @vscode/vsce
          vsce package

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vsce-package
          path: "*.vsix"
