name: Publish Extension

on:
  push:
    tags:
      - '*'  # O workflow será acionado em qualquer tag criada

jobs:
  build-and-approve:
    name: Build and Approve
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Ou a versão do Node.js que você usa

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Package Extension
        run: |
          npm install -g @vscode/vsce
          vsce package

      - name: Request Approval
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'manual_approval',
              client_payload: {}
            })

  publish:
    name: Publish to VSCode Marketplace
    runs-on: ubuntu-latest
    needs: build-and-approve

    steps:
      - name: Wait for Approval
        uses: chetan/invoke-action@v2
        with:
          workflow: 'Publish Extension'
          token: ${{ secrets.GITHUB_TOKEN }}
          status: approval

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Ou a versão do Node.js que você usa

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Package Extension
        run: |
          npm install -g @vscode/vsce
          vsce package

      - name: Publish Extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish
